package com.tarun.scms;

import java.sql.*;

public final class DatabaseManager {
    private static final String URL = "jdbc:h2:./data/studentdb;AUTO_SERVER=TRUE";
    private static final String USER = "sa";
    private static final String PASSWORD = "";

    private DatabaseManager() {}

    public static Connection getConnection() throws SQLException {
        return DriverManager.getConnection(URL, USER, PASSWORD);
    }

    public static void initialize() {
        String sql =
            "CREATE TABLE IF NOT EXISTS students (" +
            "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
            "roll_no VARCHAR(40) UNIQUE NOT NULL," +
            "name VARCHAR(100) NOT NULL," +
            "course VARCHAR(100) NOT NULL," +
            "marks DOUBLE NOT NULL)";
        try (Connection con = getConnection();
             Statement st = con.createStatement()) {
            st.execute(sql);
        } catch (SQLException e) {
            throw new AppException("Database initialization failed.", e);
        }
    }
}
